name: nf-core module tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nf-core-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: '24.04.1'

      - name: Set up nf-core tools
        run: pip install nf-core==2.14.1

      - name: Download Zenodo Chlamydia trachomatis cgMLST background data
        run: curl -sL -o /tmp/zenodo_bg.zip "https://zenodo.org/records/19120159/files/02_input_to_setup_cgMLST_1230_background.zip?download=1" && unzip -o /tmp/zenodo_bg.zip -d /tmp/

      - name: Run nf-core modules test
        run: nf-core modules test reportree --dir .
        env:
          PROFILE: docker

      - name: Run Python unit tests
        run: python3 tests/test_module.py
